version: "3"
services:
  frontend:
    build: .\frontend\frontapp\
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    environment:
      - PORT=${FRONTEND_PORT}
      - API_PORT=${API_SERVER_PORT}
  apiserver:
    build: .\apisevrer\
    ports:
      - "${API_SERVER_PORT}:${API_SERVER_PORT}"

    environment:
      - PORT=${API_SERVER_PORT}
