devices:
  - device1:
      - ID: 1
      - IP: 10.0.0.7
      - ENDPOINTS:
          - light1:
              - Type: LED
          - light2:
              - Type: LED
  - device2:
      - ID: 2
      - IP: 10.0.0.8
      - ENDPOINTS:
          - light1:
              - Type: LED
          - light2:
              - Type: LED
  - device3:
      - ID: 3
      - IP: 10.0.0.9
      - ENDPOINTS:
          - light1:
              - Type: LED
          - light2:
              - Type: LED
