devices:
  - device1:
      ID: 1
      IP: 10.0.0.7
      ENDPOINTS:
        - light1:
            Type: light
            subType: LED
            lightID: 1
        - light2:
            Type: light
            subType: LED
            lightID: 2
  - device2:
      ID: 2
      IP: 10.0.0.8
      ENDPOINTS:
        - light3:
            Type: light
            subType: LED
            lightID: 3
        - light4:
            Type: light
            subType: LED
            lightID: 4
  - device3:
      ID: 3
      IP: 10.0.0.9
      ENDPOINTS:
        - light5:
            Type: light
            subType: LED
            lightID: 5
        - light6:
            Type: light
            subType: LED
            lightID: 6
